services:
    math:
        container_name: ft_math
        build:
            context: ../../
            dockerfile: apps/games/math/Dockerfile
            #change target from development to final for production build
            target: development
            #target: final
        env_file: ../../.env
        environment:
            - PORT=3001
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            redis:
                condition: service_healthy
        volumes:
            - ../../apps/games/math/src:/app/apps/games/math/src
            - ../../libs/types/src:/app/libs/types/src
        networks:
            - ft_network
        restart: unless-stopped
    reaction-time:
        container_name: ft_reaction-time
        build:
            context: ../../
            dockerfile: apps/games/reaction-time/Dockerfile
            target: development
        env_file: ../../.env
        environment:
            - PORT=3002
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            redis:
                condition: service_healthy
        volumes:
            - ../../apps/games/reaction-time/src:/app/apps/games/reaction-time/src
            - ../../libs/types/src:/app/libs/types/src
        networks:
            - ft_network
        restart: unless-stopped

